name: Docs

on:
  push:
    branches: [ main ]

jobs:
  build_and_lint:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v2

        uses: actions/cache@v2
        id: node-cache
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('yarn-lock.json') }}

        if: steps.node-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Create the docs directory locally in CI
        run: yarn typedoc src/index.ts

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: docs
